{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/configuration(_:_:_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/ErrorDescription","text":"ErrorDescription","preciseIdentifier":"s:7Amplify16ErrorDescriptiona"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7Amplify18RecoverySuggestiona","text":"RecoverySuggestion","kind":"typeIdentifier","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"]]},"metadata":{"externalID":"s:7Amplify9AuthErrorO13configurationyACSS_SSs0C0_pSgtcACmF","title":"AuthError.configuration(_:_:_:)","roleHeading":"Case","role":"symbol","modules":[{"name":"Amplify"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":"("},{"text":"ErrorDescription","preciseIdentifier":"s:7Amplify16ErrorDescriptiona","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"RecoverySuggestion","preciseIdentifier":"s:7Amplify18RecoverySuggestiona"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}]},"abstract":[{"type":"text","text":"Caused by issue in the way auth category is configured"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/autherror\/configuration(_:_:_:)"]}],"references":{"x-source-tag://AmplifyError.errorDescription":{"title":"AmplifyError.errorDescription","identifier":"x-source-tag:\/\/AmplifyError.errorDescription","type":"link","titleInlineContent":[{"text":"AmplifyError.errorDescription","type":"text"}],"url":"x-source-tag:\/\/AmplifyError.errorDescription"},"x-source-tag://AmplifyError.recoverySuggestion":{"title":"AmplifyError.recoverySuggestion","identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion","type":"link","titleInlineContent":[{"text":"AmplifyError.recoverySuggestion","type":"text"}],"url":"x-source-tag:\/\/AmplifyError.recoverySuggestion"},"doc://amplify-swift.Amplify/documentation/Amplify/ErrorDescription":{"url":"\/documentation\/amplify\/errordescription","title":"ErrorDescription","type":"topic","abstract":[{"type":"text","text":"See: "},{"type":"reference","identifier":"x-source-tag:\/\/AmplifyError.errorDescription","isActive":true}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/ErrorDescription","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorDescription"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorDescription"}]},"doc://amplify-swift.Amplify/documentation/Amplify/RecoverySuggestion":{"url":"\/documentation\/amplify\/recoverysuggestion","title":"RecoverySuggestion","type":"topic","abstract":[{"type":"text","text":"See: "},{"identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion","type":"reference","isActive":true}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecoverySuggestion","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RecoverySuggestion","kind":"identifier"}]},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError/configuration(_:_:_:)":{"url":"\/documentation\/amplify\/autherror\/configuration(_:_:_:)","role":"symbol","abstract":[{"text":"Caused by issue in the way auth category is configured","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ErrorDescription","preciseIdentifier":"s:7Amplify16ErrorDescriptiona","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"RecoverySuggestion","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify18RecoverySuggestiona"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/configuration(_:_:_:)","kind":"symbol","type":"topic","title":"AuthError.configuration(_:_:_:)"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError":{"navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"kind":"symbol","role":"symbol","url":"\/documentation\/amplify\/autherror","title":"AuthError","type":"topic","abstract":[{"type":"text","text":"Amplify error raised in the Auth category."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"}}}