{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"]]},"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/invalidState(_:_:_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/autherror\/invalidstate(_:_:_:)"]}],"sections":[],"metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidState","kind":"identifier"},{"kind":"text","text":"("},{"text":"ErrorDescription","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify16ErrorDescriptiona"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7Amplify18RecoverySuggestiona","text":"RecoverySuggestion","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?)","kind":"text"}],"title":"AuthError.invalidState(_:_:_:)","role":"symbol","externalID":"s:7Amplify9AuthErrorO12invalidStateyACSS_SSs0C0_pSgtcACmF","modules":[{"name":"Amplify"}]},"abstract":[{"type":"text","text":"Caused when an operation is not valid with the current state of Auth category"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidState","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/ErrorDescription","text":"ErrorDescription","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify16ErrorDescriptiona"},{"text":", ","kind":"text"},{"text":"RecoverySuggestion","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify18RecoverySuggestiona"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]}],"references":{"doc://amplify-swift.Amplify/documentation/Amplify/AuthError/invalidState(_:_:_:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidState"},{"kind":"text","text":"("},{"text":"ErrorDescription","preciseIdentifier":"s:7Amplify16ErrorDescriptiona","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"RecoverySuggestion","preciseIdentifier":"s:7Amplify18RecoverySuggestiona","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"AuthError.invalidState(_:_:_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/invalidState(_:_:_:)","url":"\/documentation\/amplify\/autherror\/invalidstate(_:_:_:)","abstract":[{"text":"Caused when an operation is not valid with the current state of Auth category","type":"text"}],"role":"symbol"},"x-source-tag://AmplifyError.errorDescription":{"identifier":"x-source-tag:\/\/AmplifyError.errorDescription","type":"link","title":"AmplifyError.errorDescription","titleInlineContent":[{"text":"AmplifyError.errorDescription","type":"text"}],"url":"x-source-tag:\/\/AmplifyError.errorDescription"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/ErrorDescription":{"url":"\/documentation\/amplify\/errordescription","title":"ErrorDescription","type":"topic","abstract":[{"type":"text","text":"See: "},{"type":"reference","identifier":"x-source-tag:\/\/AmplifyError.errorDescription","isActive":true}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/ErrorDescription","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorDescription"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ErrorDescription"}]},"doc://amplify-swift.Amplify/documentation/Amplify/RecoverySuggestion":{"url":"\/documentation\/amplify\/recoverysuggestion","title":"RecoverySuggestion","type":"topic","abstract":[{"type":"text","text":"See: "},{"identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion","type":"reference","isActive":true}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecoverySuggestion","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RecoverySuggestion","kind":"identifier"}]},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError":{"navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"kind":"symbol","role":"symbol","url":"\/documentation\/amplify\/autherror","title":"AuthError","type":"topic","abstract":[{"type":"text","text":"Amplify error raised in the Auth category."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"},"x-source-tag://AmplifyError.recoverySuggestion":{"identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion","type":"link","title":"AmplifyError.recoverySuggestion","titleInlineContent":[{"type":"text","text":"AmplifyError.recoverySuggestion"}],"url":"x-source-tag:\/\/AmplifyError.recoverySuggestion"}}}