{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/amplifyerror\/isoperationcancellederror"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"s:7Amplify0A5ErrorPAAE020isOperationCancelledB0Sbvp","role":"symbol","roleHeading":"Instance Property","title":"isOperationCancelledError","symbolKind":"property","extendedModule":"Amplify","modules":[{"name":"Amplify"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isOperationCancelledError","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isOperationCancelledError"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError\/isOperationCancelledError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError"]]},"kind":"symbol","references":{"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyError":{"navigatorTitle":[{"kind":"identifier","text":"AmplifyError"}],"role":"symbol","title":"AmplifyError","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError","abstract":[{"type":"text","text":"Amplifyâ€™s philosophy is to expose friendly error messages to the customer that assist with debugging."},{"type":"text","text":" "},{"type":"text","text":"Therefore, failable APIs are declared to return error results with Amplify errors, which require"},{"type":"text","text":" "},{"type":"text","text":"recovery suggestions and error messages."}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AmplifyError"}],"url":"\/documentation\/amplify\/amplifyerror"},"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyError/isOperationCancelledError":{"title":"isOperationCancelledError","url":"\/documentation\/amplify\/amplifyerror\/isoperationcancellederror","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError\/isOperationCancelledError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isOperationCancelledError","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic"}}}