{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/InternalTaskValue"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/InternalTaskValue\/Failure"},"metadata":{"role":"symbol","roleHeading":"Associated Type","title":"Failure","externalID":"s:7Amplify17InternalTaskValueP7FailureQa","fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AmplifyError","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify0A5ErrorP"}],"required":true,"modules":[{"name":"Amplify"}],"symbolKind":"associatedtype"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError","preciseIdentifier":"s:7Amplify0A5ErrorP","text":"AmplifyError"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/internaltaskvalue\/failure"]}],"sections":[],"references":{"doc://amplify-swift.Amplify/documentation/Amplify/InternalTaskValue":{"abstract":[],"type":"topic","url":"\/documentation\/amplify\/internaltaskvalue","navigatorTitle":[{"kind":"identifier","text":"InternalTaskValue"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/InternalTaskValue","title":"InternalTaskValue","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InternalTaskValue"}]},"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyError":{"navigatorTitle":[{"kind":"identifier","text":"AmplifyError"}],"role":"symbol","title":"AmplifyError","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError","abstract":[{"type":"text","text":"Amplifyâ€™s philosophy is to expose friendly error messages to the customer that assist with debugging."},{"type":"text","text":" "},{"type":"text","text":"Therefore, failable APIs are declared to return error results with Amplify errors, which require"},{"type":"text","text":" "},{"type":"text","text":"recovery suggestions and error messages."}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AmplifyError"}],"url":"\/documentation\/amplify\/amplifyerror"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/InternalTaskValue/Failure":{"role":"symbol","title":"Failure","type":"topic","url":"\/documentation\/amplify\/internaltaskvalue\/failure","kind":"symbol","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/InternalTaskValue\/Failure","abstract":[],"required":true,"fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Failure"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:7Amplify0A5ErrorP","text":"AmplifyError","kind":"typeIdentifier"}]}}}