{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyTaskExecution"]]},"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyTaskExecution\/Failure","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/amplifytaskexecution\/failure"]}],"sections":[],"metadata":{"roleHeading":"Associated Type","externalID":"s:7Amplify0A13TaskExecutionP7FailureQa","role":"symbol","symbolKind":"associatedtype","modules":[{"name":"Amplify"}],"title":"Failure","required":true,"fragments":[{"kind":"keyword","text":"associatedtype"},{"kind":"text","text":" "},{"text":"Failure","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AmplifyError","preciseIdentifier":"s:7Amplify0A5ErrorP","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"AmplifyError","kind":"typeIdentifier","preciseIdentifier":"s:7Amplify0A5ErrorP","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyTaskExecution/Failure":{"abstract":[],"kind":"symbol","required":true,"fragments":[{"text":"associatedtype","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Failure","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:7Amplify0A5ErrorP","text":"AmplifyError"}],"role":"symbol","type":"topic","url":"\/documentation\/amplify\/amplifytaskexecution\/failure","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyTaskExecution\/Failure","title":"Failure"},"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyTaskExecution":{"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyTaskExecution","role":"symbol","abstract":[{"text":"Task that supports hub with execution of a single unit of work. .","type":"text"}],"navigatorTitle":[{"text":"AmplifyTaskExecution","kind":"identifier"}],"kind":"symbol","type":"topic","title":"AmplifyTaskExecution","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AmplifyTaskExecution","kind":"identifier"}],"url":"\/documentation\/amplify\/amplifytaskexecution"},"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyError":{"navigatorTitle":[{"kind":"identifier","text":"AmplifyError"}],"role":"symbol","title":"AmplifyError","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError","abstract":[{"type":"text","text":"Amplifyâ€™s philosophy is to expose friendly error messages to the customer that assist with debugging."},{"type":"text","text":" "},{"type":"text","text":"Therefore, failable APIs are declared to return error results with Amplify errors, which require"},{"type":"text","text":" "},{"type":"text","text":"recovery suggestions and error messages."}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AmplifyError"}],"url":"\/documentation\/amplify\/amplifyerror"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]}}}